### ISSUE TITLE
The object 'UQ__core_mem__B9BE370E8A575F1B' is dependent on column

### ISSUE THREAD

**Issue by bilal414** [michiya/django-pyodbc-azure#51] opened 2016-02-21 10:36 UTC
Hi I have following model. 

class CoreMember(models.Model):

```
user = models.OneToOneField(User, related_name='member')

name = models.CharField(max_length=255, null=True)

class Meta():
    db_table = 'core_member'
```

when I try to remove "user" field I get following error. 

django.db.utils.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]The object 'UQ__core_mem__B9BE370E8A575F1B' is dependent on column 'user_id'. (5074) (SQLExecDirectW); [42000] [Microsoft][ODBC S
QL Server Driver][SQL Server]ALTER TABLE DROP COLUMN user_id failed because one or more objects access this column. (4922)")

any idea?

**Comment by michiya** [comment] 2016-03-06 04:56
@bilal414 Thank you for reporting!

This was a bug in the backend. I've pushed the new version of the backend to PyPI that includes the fix for this. Please let me know if you still have the same error after upgrading the backend to the new one.

**Comment by michiya** [comment] 2016-08-18 13:45
Marking this issue as closed because the fix for the issue is now available on PyPI as a part of the latest version of django-pyodbc-azure. Please open a new issue if you're still experiencing problems.

**Closed as completed by michiya** 2016-08-18 13:45 UTC
