### ISSUE TITLE
Override Port Number Ignored

### ISSUE THREAD

**Issue by ghost** [michiya/django-pyodbc-azure#112] opened 2017-10-24 12:47 UTC
Hi,

I have the following configuration (some values changed for privacy).

```
 {
            'default': {
                'NAME': 'pz_sme',
                'ENGINE': 'sql_server.pyodbc',
                'HOST': '11.222.123.136',
                'PORT': 14436,  
                'USER': 'user_restricted',
                'PASSWORD': 'password',
                'OPTIONS': {
                    'driver': 'SQL Server',
                    'host_is_server': True
                }
            }
        }
```

When I try to run `python manage.py migrate` with this configuration the windows firewall log, logs connection attempts with port 1433 and not 14436 as specified within my config. This fails for both when PORT is a string or int. The django application logs also log access denied (this is on a remote server though)

I suspect the default (1433) port number is being used even though I am setting (14436). 

Locally, if I enter in complete garbage as the port number i.e. 123456 it some how still connects??

I tried looking at this repo code to identify where the port number is read and used but failed. 

Could someone help me please.

Thanks
Sanjay

**Comment by ghost** [comment] 2017-10-24 15:46
Found out the cause. 

If you use a IP address for the HOST, the PORT is ignored.

Is this a bug?

**Comment by twschiller** [comment] 2018-01-02 17:21
I think the problem might be how the library is passing the PORT in the connection string to `pyodbc`. The PORT is passed using `PORT=`:

    DRIVER=ODBC Driver 13 for SQL Server;PORT=32771;SERVER=localhost;UID=sa;PWD=P@ssW0rd!;DATABASE=test-db;MARS_Connection=yes

Where generally the PORT should be included after the server with a comma:

    DRIVER=ODBC Driver 13 for SQL Server;SERVER=localhost,32771;UID=sa;PWD=P@ssW0rd!;DATABASE=test-db;MARS_Connection=yes

I don't see any documentation at https://github.com/mkleehammer/pyodbc/wiki supporting `PORT=` as a valid way to pass the port number.

I haven't looked through the `pyodbc` source yet the see if it's an undocumented feature. But fixing the port number in the connection string produced by `django-pyodbc-azure` is a valid connection string for `pyodbc`

**Comment by nyejon** [comment] 2018-01-08 10:30
If I use my database host as 'database.host.name,port' then it connects - I was having trouble from linux where the driver cannot automatically determine the port number of a named instance. As stated the 'PORT' database setting appears to do nothing

**Comment by michiya** [comment] 2018-03-10 16:18
The issue is fixed in the latest release. Try it out and let me know if you still have the same issue.

**Closed as completed by michiya** 2018-03-10 16:18 UTC
