### ISSUE TITLE
Add Support for SQL Server vNext

### ISSUE THREAD

**Issue by csucla2015** [michiya/django-pyodbc-azure#81] opened 2016-12-08 21:54 UTC
SQL Server vNext is using v14.x. Check out the getting started guide here: https://www.microsoft.com/en-us/sql-server/developer-get-started/python-ubuntu

Can we add support for v14 in base.py? https://www.microsoft.com/en-us/sql-server/developer-get-started/python-ubuntu 

Thanks 👍

**Comment by markhepburn** [comment] 2016-12-15 12:09
Just came to post this, thanks.

(For what it's worth, I was able to get a django project to work using the [1.8 driver](https://github.com/michiya/django-pyodbc-azure/blob/azure-1.8/sql_server/pyodbc/base.py#L150), although it hasn't been pushed hard -- works well enough for my local dev environment though)

**Comment by kevin-brown** [comment] 2016-12-18 19:00
Looks like this was done in https://github.com/michiya/django-pyodbc-azure/commit/d70ed8f115f3062f54f7b739b23ccece09ec9bae.

**Comment by michiya** [comment] 2016-12-19 13:41
Thank you for letting me know. I've also confirmed that django-pyodbc-azure works well with SQL Server vNext CTP 1.1. You can grab the new version of django-pyodbc-azure that supports SQL Server vNext from PyPI now.

**Comment by michiya** [comment] 2017-01-05 10:05
Closing the issue because the new version of the package that contains the fix for this is available on PyPI.

**Closed as completed by michiya** 2017-01-05 10:05 UTC
