### ISSUE TITLE
Returning Django DateTimeField() as Python datetime object?

### ISSUE THREAD

**Issue by FlipperPA** [michiya/django-pyodbc-azure#44] opened 2015-09-22 20:04 UTC
In Postgres (and other DBs), DateTimeField() fields are returned as datetime objects. I may be missing something, but here's the issue I'm having. I'm running Django 1.7.9 on Python 3.3.5 with SQL Server 2014 over FreeTDS 0.91 and pyodbc. I have a DateTimeField:

```
begin_date = models.DateTimeField(db_column='period_begin_date')
```

After migrating, it appears in the database as:

```
period_begin_date(datetime2(7), not null)
```

So far, so good. When I insert fields, they're getting inserted correctly into SQL Server. However, when I get an object from the Python shell:

```
----> 1 print(bt.begin_period.month)
AttributeError: 'Period' object has no attribute 'month'
```

Any ideas why? Is it the FreeTDS version conflicting on types?

**Comment by michiya** [comment] 2015-11-20 03:10
Hi,

It seems to me that the error is produced because of the same reason as #15, and I wonder why the DateTimeField is rendered as `datetime2` type in your databasle because the backend assigns `datetime` type for a DateTimeField at migrations when you employ FreeTDS v0.91. Did you perhaps apply migrations with other ODBC drivers or other backend adapters?

**Comment by michiya** [comment] 2017-01-05 10:31
Closing the issue because I believe the issue is the same as #63 and #70 and is already resolved. Feel free to open a new issue if you still have a problem.

**Closed as completed by michiya** 2017-01-05 10:31 UTC
